# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './maindialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainDialog(object):
    def setupUi(self, MainDialog):
        MainDialog.setObjectName("MainDialog")
        MainDialog.resize(814, 548)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Downloads/st_mark_icons/st_mark_iTO_2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(MainDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(MainDialog)
        self.tabWidget.setMinimumSize(QtCore.QSize(796, 515))
        self.tabWidget.setMaximumSize(QtCore.QSize(1500, 3303))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(237, 9, 16, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.st_tableWidget = QtWidgets.QTableWidget(self.tab)
        self.st_tableWidget.setGeometry(QtCore.QRect(9, 38, 771, 411))
        self.st_tableWidget.setObjectName("st_tableWidget")
        self.st_tableWidget.setColumnCount(5)
        self.st_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.st_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.st_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.st_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.st_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.st_tableWidget.setHorizontalHeaderItem(4, item)
        self.st_pushButton_delete = QtWidgets.QPushButton(self.tab)
        self.st_pushButton_delete.setGeometry(QtCore.QRect(30, 460, 80, 26))
        self.st_pushButton_delete.setMinimumSize(QtCore.QSize(80, 26))
        self.st_pushButton_delete.setMaximumSize(QtCore.QSize(75, 26))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        self.st_pushButton_delete.setFont(font)
        self.st_pushButton_delete.setAutoDefault(False)
        self.st_pushButton_delete.setObjectName("st_pushButton_delete")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(530, 9, 251, 28))
        self.widget.setObjectName("widget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.st_lineEdit_search = QtWidgets.QLineEdit(self.widget)
        self.st_lineEdit_search.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.st_lineEdit_search.setObjectName("st_lineEdit_search")
        self.horizontalLayout_12.addWidget(self.st_lineEdit_search)
        self.st_pushButton_search = QtWidgets.QPushButton(self.widget)
        self.st_pushButton_search.setMinimumSize(QtCore.QSize(75, 26))
        self.st_pushButton_search.setStyleSheet("font: 10pt \"나눔스퀘어\";\n"
"")
        self.st_pushButton_search.setObjectName("st_pushButton_search")
        self.horizontalLayout_12.addWidget(self.st_pushButton_search)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.s_lineEdit_ID = QtWidgets.QLineEdit(self.tab_3)
        self.s_lineEdit_ID.setGeometry(QtCore.QRect(463, 52, 169, 26))
        self.s_lineEdit_ID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s_lineEdit_ID.setObjectName("s_lineEdit_ID")
        self.s_dateEdit = QtWidgets.QDateEdit(self.tab_3)
        self.s_dateEdit.setGeometry(QtCore.QRect(180, 52, 121, 26))
        self.s_dateEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 7, 1), QtCore.QTime(0, 0, 0)))
        self.s_dateEdit.setObjectName("s_dateEdit")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(355, 52, 102, 20))
        self.label_9.setObjectName("label_9")
        self.s_lineEdit_name = QtWidgets.QLineEdit(self.tab_3)
        self.s_lineEdit_name.setGeometry(QtCore.QRect(180, 84, 169, 26))
        self.s_lineEdit_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s_lineEdit_name.setObjectName("s_lineEdit_name")
        self.s_tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.s_tableWidget.setGeometry(QtCore.QRect(9, 150, 771, 291))
        self.s_tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.s_tableWidget.setObjectName("s_tableWidget")
        self.s_tableWidget.setColumnCount(6)
        self.s_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.s_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.s_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.s_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.s_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.s_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.s_tableWidget.setHorizontalHeaderItem(5, item)
        self.s_lineEdit_price = QtWidgets.QLineEdit(self.tab_3)
        self.s_lineEdit_price.setGeometry(QtCore.QRect(463, 84, 169, 26))
        self.s_lineEdit_price.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s_lineEdit_price.setObjectName("s_lineEdit_price")
        self.s_pushButton_com_search = QtWidgets.QPushButton(self.tab_3)
        self.s_pushButton_com_search.setGeometry(QtCore.QRect(29, 9, 75, 26))
        self.s_pushButton_com_search.setStyleSheet("font: 10pt \"나눔스퀘어\";\n"
"")
        self.s_pushButton_com_search.setAutoDefault(False)
        self.s_pushButton_com_search.setObjectName("s_pushButton_com_search")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(72, 116, 97, 20))
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(355, 84, 97, 20))
        self.label_13.setObjectName("label_13")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(72, 84, 97, 20))
        self.label_12.setObjectName("label_12")
        self.s_pushButton_product_search = QtWidgets.QPushButton(self.tab_3)
        self.s_pushButton_product_search.setGeometry(QtCore.QRect(690, 9, 75, 26))
        self.s_pushButton_product_search.setStyleSheet("font: 10pt \"나눔스퀘어\";\n"
"")
        self.s_pushButton_product_search.setAutoDefault(False)
        self.s_pushButton_product_search.setObjectName("s_pushButton_product_search")
        self.line = QtWidgets.QFrame(self.tab_3)
        self.line.setGeometry(QtCore.QRect(23, 30, 761, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(72, 52, 97, 20))
        self.label_15.setObjectName("label_15")
        self.widget1 = QtWidgets.QWidget(self.tab_3)
        self.widget1.setGeometry(QtCore.QRect(30, 450, 731, 28))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.s_pushButton_delete = QtWidgets.QPushButton(self.widget1)
        self.s_pushButton_delete.setMinimumSize(QtCore.QSize(75, 26))
        self.s_pushButton_delete.setStyleSheet("font: 10pt \"나눔스퀘어\";\n"
"")
        self.s_pushButton_delete.setAutoDefault(False)
        self.s_pushButton_delete.setObjectName("s_pushButton_delete")
        self.horizontalLayout_2.addWidget(self.s_pushButton_delete)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.s_label = QtWidgets.QLabel(self.widget1)
        self.s_label.setMaximumSize(QtCore.QSize(35, 16777215))
        self.s_label.setObjectName("s_label")
        self.horizontalLayout.addWidget(self.s_label)
        self.s_label_total_price = QtWidgets.QLabel(self.widget1)
        self.s_label_total_price.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s_label_total_price.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s_label_total_price.setObjectName("s_label_total_price")
        self.horizontalLayout.addWidget(self.s_label_total_price)
        self.label_21 = QtWidgets.QLabel(self.widget1)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout.addWidget(self.label_21)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.s_pushButton_selling = QtWidgets.QPushButton(self.widget1)
        self.s_pushButton_selling.setMinimumSize(QtCore.QSize(75, 26))
        self.s_pushButton_selling.setStyleSheet("font: 10pt \"나눔스퀘어\";\n"
"")
        self.s_pushButton_selling.setAutoDefault(False)
        self.s_pushButton_selling.setObjectName("s_pushButton_selling")
        self.horizontalLayout_2.addWidget(self.s_pushButton_selling)
        self.widget2 = QtWidgets.QWidget(self.tab_3)
        self.widget2.setGeometry(QtCore.QRect(110, 10, 150, 22))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_23 = QtWidgets.QLabel(self.widget2)
        self.label_23.setMinimumSize(QtCore.QSize(70, 0))
        self.label_23.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_17.addWidget(self.label_23)
        self.s_label_com = QtWidgets.QLabel(self.widget2)
        self.s_label_com.setText("")
        self.s_label_com.setObjectName("s_label_com")
        self.horizontalLayout_17.addWidget(self.s_label_com)
        self.widget3 = QtWidgets.QWidget(self.tab_3)
        self.widget3.setGeometry(QtCore.QRect(180, 116, 451, 28))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.s_lineEdit_num = QtWidgets.QLineEdit(self.widget3)
        self.s_lineEdit_num.setMinimumSize(QtCore.QSize(0, 26))
        self.s_lineEdit_num.setMaximumSize(QtCore.QSize(169, 16777215))
        self.s_lineEdit_num.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s_lineEdit_num.setObjectName("s_lineEdit_num")
        self.horizontalLayout_18.addWidget(self.s_lineEdit_num)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem3)
        self.s_pushButton_add = QtWidgets.QPushButton(self.widget3)
        self.s_pushButton_add.setMinimumSize(QtCore.QSize(75, 26))
        self.s_pushButton_add.setStyleSheet("font: 10pt \"나눔스퀘어\";\n"
"")
        self.s_pushButton_add.setAutoDefault(False)
        self.s_pushButton_add.setObjectName("s_pushButton_add")
        self.horizontalLayout_18.addWidget(self.s_pushButton_add)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.b_pushButton_add = QtWidgets.QPushButton(self.tab_2)
        self.b_pushButton_add.setGeometry(QtCore.QRect(580, 70, 81, 26))
        self.b_pushButton_add.setStyleSheet("font: 10pt \"나눔스퀘어\";\n"
"")
        self.b_pushButton_add.setAutoDefault(False)
        self.b_pushButton_add.setObjectName("b_pushButton_add")
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setGeometry(QtCore.QRect(9, 92, 772, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.b_tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.b_tableWidget.setGeometry(QtCore.QRect(9, 140, 771, 341))
        self.b_tableWidget.setObjectName("b_tableWidget")
        self.b_tableWidget.setColumnCount(5)
        self.b_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.b_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.b_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.b_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.b_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.b_tableWidget.setHorizontalHeaderItem(4, item)
        self.b_tableWidget.horizontalHeader().setMinimumSectionSize(21)
        self.b_tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.b_tableWidget.verticalHeader().setMinimumSectionSize(28)
        self.b_pushButton_bring = QtWidgets.QPushButton(self.tab_2)
        self.b_pushButton_bring.setGeometry(QtCore.QRect(20, 110, 75, 26))
        self.b_pushButton_bring.setStyleSheet("font: 10pt \"나눔스퀘어\";\n"
"")
        self.b_pushButton_bring.setAutoDefault(False)
        self.b_pushButton_bring.setObjectName("b_pushButton_bring")
        self.widget4 = QtWidgets.QWidget(self.tab_2)
        self.widget4.setGeometry(QtCore.QRect(502, 110, 261, 28))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b_lineEdit_search = QtWidgets.QLineEdit(self.widget4)
        self.b_lineEdit_search.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b_lineEdit_search.setObjectName("b_lineEdit_search")
        self.horizontalLayout_3.addWidget(self.b_lineEdit_search)
        self.b_pushButton_search = QtWidgets.QPushButton(self.widget4)
        self.b_pushButton_search.setMinimumSize(QtCore.QSize(75, 26))
        self.b_pushButton_search.setStyleSheet("\n"
"font: 10pt \"나눔스퀘어\";")
        self.b_pushButton_search.setAutoDefault(False)
        self.b_pushButton_search.setObjectName("b_pushButton_search")
        self.horizontalLayout_3.addWidget(self.b_pushButton_search)
        self.widget5 = QtWidgets.QWidget(self.tab_2)
        self.widget5.setGeometry(QtCore.QRect(60, 10, 281, 28))
        self.widget5.setObjectName("widget5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.widget5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.b_lineEdit_ID = QtWidgets.QLineEdit(self.widget5)
        self.b_lineEdit_ID.setMinimumSize(QtCore.QSize(0, 26))
        self.b_lineEdit_ID.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.b_lineEdit_ID.setText("")
        self.b_lineEdit_ID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b_lineEdit_ID.setObjectName("b_lineEdit_ID")
        self.horizontalLayout_7.addWidget(self.b_lineEdit_ID)
        self.widget6 = QtWidgets.QWidget(self.tab_2)
        self.widget6.setGeometry(QtCore.QRect(60, 40, 281, 28))
        self.widget6.setObjectName("widget6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.widget6)
        self.label_5.setMaximumSize(QtCore.QSize(92, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.b_lineEdit_com = QtWidgets.QLineEdit(self.widget6)
        self.b_lineEdit_com.setMinimumSize(QtCore.QSize(0, 26))
        self.b_lineEdit_com.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b_lineEdit_com.setObjectName("b_lineEdit_com")
        self.horizontalLayout_8.addWidget(self.b_lineEdit_com)
        self.widget7 = QtWidgets.QWidget(self.tab_2)
        self.widget7.setGeometry(QtCore.QRect(60, 70, 281, 28))
        self.widget7.setObjectName("widget7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.widget7)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.b_lineEdit_num = QtWidgets.QLineEdit(self.widget7)
        self.b_lineEdit_num.setMinimumSize(QtCore.QSize(0, 26))
        self.b_lineEdit_num.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b_lineEdit_num.setObjectName("b_lineEdit_num")
        self.horizontalLayout_9.addWidget(self.b_lineEdit_num)
        self.widget8 = QtWidgets.QWidget(self.tab_2)
        self.widget8.setGeometry(QtCore.QRect(400, 10, 261, 28))
        self.widget8.setObjectName("widget8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget8)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.widget8)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.b_lineEdit_name = QtWidgets.QLineEdit(self.widget8)
        self.b_lineEdit_name.setMinimumSize(QtCore.QSize(0, 26))
        self.b_lineEdit_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b_lineEdit_name.setObjectName("b_lineEdit_name")
        self.horizontalLayout_10.addWidget(self.b_lineEdit_name)
        self.widget9 = QtWidgets.QWidget(self.tab_2)
        self.widget9.setGeometry(QtCore.QRect(400, 40, 261, 28))
        self.widget9.setObjectName("widget9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget9)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.widget9)
        self.label_6.setMaximumSize(QtCore.QSize(92, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.b_lineEdit_price = QtWidgets.QLineEdit(self.widget9)
        self.b_lineEdit_price.setMinimumSize(QtCore.QSize(0, 26))
        self.b_lineEdit_price.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b_lineEdit_price.setObjectName("b_lineEdit_price")
        self.horizontalLayout_11.addWidget(self.b_lineEdit_price)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_com_serach_receive = QtWidgets.QLabel(self.tab_4)
        self.label_com_serach_receive.setGeometry(QtCore.QRect(288, 455, 16, 16))
        self.label_com_serach_receive.setText("")
        self.label_com_serach_receive.setObjectName("label_com_serach_receive")
        self.c_pushButton_com_search = QtWidgets.QPushButton(self.tab_4)
        self.c_pushButton_com_search.setGeometry(QtCore.QRect(20, 10, 75, 26))
        self.c_pushButton_com_search.setMinimumSize(QtCore.QSize(75, 26))
        self.c_pushButton_com_search.setMaximumSize(QtCore.QSize(75, 26))
        self.c_pushButton_com_search.setStyleSheet("font: 10pt \"나눔스퀘어\";\n"
"")
        self.c_pushButton_com_search.setAutoDefault(False)
        self.c_pushButton_com_search.setObjectName("c_pushButton_com_search")
        self.c_dateEdit_from = QtWidgets.QDateEdit(self.tab_4)
        self.c_dateEdit_from.setGeometry(QtCore.QRect(76, 55, 115, 21))
        self.c_dateEdit_from.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.c_dateEdit_from.setObjectName("c_dateEdit_from")
        self.c_dateEdit_to = QtWidgets.QDateEdit(self.tab_4)
        self.c_dateEdit_to.setGeometry(QtCore.QRect(210, 55, 115, 21))
        self.c_dateEdit_to.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 6, 1), QtCore.QTime(0, 0, 0)))
        self.c_dateEdit_to.setObjectName("c_dateEdit_to")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(195, 55, 16, 16))
        self.label_14.setObjectName("label_14")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(-9, 52, 70, 26))
        self.label_19.setMinimumSize(QtCore.QSize(70, 26))
        self.label_19.setMaximumSize(QtCore.QSize(70, 26))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.c_tableWidget = QtWidgets.QTableWidget(self.tab_4)
        self.c_tableWidget.setGeometry(QtCore.QRect(10, 90, 771, 351))
        self.c_tableWidget.setObjectName("c_tableWidget")
        self.c_tableWidget.setColumnCount(7)
        self.c_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.c_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.c_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.c_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.c_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.c_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.c_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.c_tableWidget.setHorizontalHeaderItem(6, item)
        self.c_pushButton_search = QtWidgets.QPushButton(self.tab_4)
        self.c_pushButton_search.setGeometry(QtCore.QRect(690, 55, 75, 26))
        self.c_pushButton_search.setMinimumSize(QtCore.QSize(75, 26))
        self.c_pushButton_search.setMaximumSize(QtCore.QSize(75, 26))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        self.c_pushButton_search.setFont(font)
        self.c_pushButton_search.setObjectName("c_pushButton_search")
        self.line_4 = QtWidgets.QFrame(self.tab_4)
        self.line_4.setGeometry(QtCore.QRect(15, 37, 761, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.widget10 = QtWidgets.QWidget(self.tab_4)
        self.widget10.setGeometry(QtCore.QRect(21, 450, 731, 30))
        self.widget10.setObjectName("widget10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget10)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.c_pushButton_delete = QtWidgets.QPushButton(self.widget10)
        self.c_pushButton_delete.setMinimumSize(QtCore.QSize(75, 26))
        self.c_pushButton_delete.setObjectName("c_pushButton_delete")
        self.horizontalLayout_6.addWidget(self.c_pushButton_delete)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.label_20 = QtWidgets.QLabel(self.widget10)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_6.addWidget(self.label_20)
        self.c_label_price = QtWidgets.QLabel(self.widget10)
        self.c_label_price.setObjectName("c_label_price")
        self.horizontalLayout_6.addWidget(self.c_label_price)
        self.label_26 = QtWidgets.QLabel(self.widget10)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_6.addWidget(self.label_26)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.label_22 = QtWidgets.QLabel(self.widget10)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_6.addWidget(self.label_22)
        self.c_label_tax = QtWidgets.QLabel(self.widget10)
        self.c_label_tax.setObjectName("c_label_tax")
        self.horizontalLayout_6.addWidget(self.c_label_tax)
        self.label_27 = QtWidgets.QLabel(self.widget10)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_6.addWidget(self.label_27)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.label_24 = QtWidgets.QLabel(self.widget10)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_6.addWidget(self.label_24)
        self.c_label_total = QtWidgets.QLabel(self.widget10)
        self.c_label_total.setObjectName("c_label_total")
        self.horizontalLayout_6.addWidget(self.c_label_total)
        self.label_28 = QtWidgets.QLabel(self.widget10)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_6.addWidget(self.label_28)
        self.widget11 = QtWidgets.QWidget(self.tab_4)
        self.widget11.setGeometry(QtCore.QRect(100, 10, 231, 28))
        self.widget11.setObjectName("widget11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget11)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_com_name = QtWidgets.QLabel(self.widget11)
        self.label_com_name.setMinimumSize(QtCore.QSize(70, 26))
        self.label_com_name.setMaximumSize(QtCore.QSize(70, 26))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_com_name.setFont(font)
        self.label_com_name.setStyleSheet("font: 10pt \"나눔스퀘어\";")
        self.label_com_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_com_name.setObjectName("label_com_name")
        self.horizontalLayout_4.addWidget(self.label_com_name)
        self.c_label_com = QtWidgets.QLabel(self.widget11)
        self.c_label_com.setText("")
        self.c_label_com.setObjectName("c_label_com")
        self.horizontalLayout_4.addWidget(self.c_label_com)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_8 = QtWidgets.QLabel(self.tab_6)
        self.label_8.setGeometry(QtCore.QRect(466, 9, 16, 16))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.r_tableWidget = QtWidgets.QTableWidget(self.tab_6)
        self.r_tableWidget.setGeometry(QtCore.QRect(9, 41, 771, 401))
        self.r_tableWidget.setObjectName("r_tableWidget")
        self.r_tableWidget.setColumnCount(2)
        self.r_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.r_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.r_tableWidget.setHorizontalHeaderItem(1, item)
        self.widget12 = QtWidgets.QWidget(self.tab_6)
        self.widget12.setGeometry(QtCore.QRect(510, 9, 267, 28))
        self.widget12.setObjectName("widget12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget12)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.r_lineEdit_search = QtWidgets.QLineEdit(self.widget12)
        self.r_lineEdit_search.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.r_lineEdit_search.setObjectName("r_lineEdit_search")
        self.horizontalLayout_13.addWidget(self.r_lineEdit_search)
        self.r_pushButton_search = QtWidgets.QPushButton(self.widget12)
        self.r_pushButton_search.setMinimumSize(QtCore.QSize(75, 26))
        self.r_pushButton_search.setStyleSheet("font: 10pt \"나눔스퀘어\";\n"
"")
        self.r_pushButton_search.setAutoDefault(False)
        self.r_pushButton_search.setObjectName("r_pushButton_search")
        self.horizontalLayout_13.addWidget(self.r_pushButton_search)
        self.widget13 = QtWidgets.QWidget(self.tab_6)
        self.widget13.setGeometry(QtCore.QRect(21, 452, 751, 32))
        self.widget13.setObjectName("widget13")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget13)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.r_pushButton_detail = QtWidgets.QPushButton(self.widget13)
        self.r_pushButton_detail.setMinimumSize(QtCore.QSize(75, 26))
        self.r_pushButton_detail.setObjectName("r_pushButton_detail")
        self.horizontalLayout_16.addWidget(self.r_pushButton_detail)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem9)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.r_lineEdit_receive = QtWidgets.QLineEdit(self.widget13)
        self.r_lineEdit_receive.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.r_lineEdit_receive.setObjectName("r_lineEdit_receive")
        self.horizontalLayout_14.addWidget(self.r_lineEdit_receive)
        self.r_pushButton_receive = QtWidgets.QPushButton(self.widget13)
        self.r_pushButton_receive.setMinimumSize(QtCore.QSize(75, 26))
        self.r_pushButton_receive.setObjectName("r_pushButton_receive")
        self.horizontalLayout_14.addWidget(self.r_pushButton_receive)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_14)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.rg_pushButton = QtWidgets.QPushButton(self.tab_5)
        self.rg_pushButton.setGeometry(QtCore.QRect(520, 250, 93, 28))
        self.rg_pushButton.setStyleSheet("font: 10.5pt \"나눔스퀘어\";\n"
"")
        self.rg_pushButton.setObjectName("rg_pushButton")
        self.layoutWidget = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 70, 351, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.rg_lineEdit_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.rg_lineEdit_name.setAlignment(QtCore.Qt.AlignCenter)
        self.rg_lineEdit_name.setObjectName("rg_lineEdit_name")
        self.gridLayout_7.addWidget(self.rg_lineEdit_name, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 2, 0, 1, 1)
        self.rg_lineEdit_num = QtWidgets.QLineEdit(self.layoutWidget)
        self.rg_lineEdit_num.setAlignment(QtCore.Qt.AlignCenter)
        self.rg_lineEdit_num.setObjectName("rg_lineEdit_num")
        self.gridLayout_7.addWidget(self.rg_lineEdit_num, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 1, 0, 1, 1)
        self.rg_lineEdit_com = QtWidgets.QLineEdit(self.layoutWidget)
        self.rg_lineEdit_com.setText("")
        self.rg_lineEdit_com.setAlignment(QtCore.Qt.AlignCenter)
        self.rg_lineEdit_com.setObjectName("rg_lineEdit_com")
        self.gridLayout_7.addWidget(self.rg_lineEdit_com, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.tab_5)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1151, 751))
        self.frame.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(550, 380, 201, 61))
        self.label_18.setStyleSheet("\n"
"font: 10pt \"배달의민족 주아\";")
        self.label_18.setObjectName("label_18")
        self.frame.raise_()
        self.rg_pushButton.raise_()
        self.layoutWidget.raise_()
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(MainDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainDialog)
        MainDialog.setTabOrder(self.b_lineEdit_ID, self.b_lineEdit_name)
        MainDialog.setTabOrder(self.b_lineEdit_name, self.b_lineEdit_com)
        MainDialog.setTabOrder(self.b_lineEdit_com, self.b_lineEdit_price)
        MainDialog.setTabOrder(self.b_lineEdit_price, self.b_lineEdit_num)
        MainDialog.setTabOrder(self.b_lineEdit_num, self.b_pushButton_add)
        MainDialog.setTabOrder(self.b_pushButton_add, self.st_lineEdit_search)
        MainDialog.setTabOrder(self.st_lineEdit_search, self.b_lineEdit_search)
        MainDialog.setTabOrder(self.b_lineEdit_search, self.st_tableWidget)
        MainDialog.setTabOrder(self.st_tableWidget, self.b_pushButton_search)
        MainDialog.setTabOrder(self.b_pushButton_search, self.st_pushButton_search)
        MainDialog.setTabOrder(self.st_pushButton_search, self.b_tableWidget)
        MainDialog.setTabOrder(self.b_tableWidget, self.b_pushButton_bring)

    def retranslateUi(self, MainDialog):
        _translate = QtCore.QCoreApplication.translate
        MainDialog.setWindowTitle(_translate("MainDialog", "Stock Manager"))
        item = self.st_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainDialog", "품번"))
        item = self.st_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainDialog", "품명"))
        item = self.st_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainDialog", "매입처"))
        item = self.st_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainDialog", "매입가"))
        item = self.st_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainDialog", "재고"))
        self.st_pushButton_delete.setText(_translate("MainDialog", "삭 제"))
        self.st_pushButton_search.setText(_translate("MainDialog", "검 색"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainDialog", "  재 고  "))
        self.label_9.setText(_translate("MainDialog", "             품번"))
        self.s_tableWidget.setSortingEnabled(True)
        item = self.s_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainDialog", "품번"))
        item = self.s_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainDialog", "품명"))
        item = self.s_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainDialog", "단가"))
        item = self.s_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainDialog", "수량"))
        item = self.s_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainDialog", "공급 가액"))
        item = self.s_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainDialog", "세액"))
        self.s_pushButton_com_search.setText(_translate("MainDialog", "회사 검색"))
        self.label_11.setText(_translate("MainDialog", "             수량"))
        self.label_13.setText(_translate("MainDialog", "             단가"))
        self.label_12.setText(_translate("MainDialog", "             품명"))
        self.s_pushButton_product_search.setText(_translate("MainDialog", "제품 검색"))
        self.label_15.setText(_translate("MainDialog", "             날짜"))
        self.s_pushButton_delete.setText(_translate("MainDialog", "삭 제"))
        self.s_label.setText(_translate("MainDialog", "합계 : "))
        self.s_label_total_price.setText(_translate("MainDialog", "0"))
        self.label_21.setText(_translate("MainDialog", "원"))
        self.s_pushButton_selling.setText(_translate("MainDialog", "판 매"))
        self.label_23.setText(_translate("MainDialog", "매출처:"))
        self.s_pushButton_add.setText(_translate("MainDialog", "추 가"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainDialog", "  매 출  "))
        self.b_pushButton_add.setText(_translate("MainDialog", "추가/감소"))
        self.b_tableWidget.setSortingEnabled(True)
        item = self.b_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainDialog", "품번"))
        item = self.b_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainDialog", "품명"))
        item = self.b_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainDialog", "매입처"))
        item = self.b_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainDialog", "매입가"))
        item = self.b_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainDialog", "재고"))
        self.b_pushButton_bring.setText(_translate("MainDialog", "가져오기"))
        self.b_pushButton_search.setText(_translate("MainDialog", "검 색"))
        self.label_3.setText(_translate("MainDialog", "            품번"))
        self.label_5.setText(_translate("MainDialog", "         매입처"))
        self.label_7.setText(_translate("MainDialog", "            갯수"))
        self.label_4.setText(_translate("MainDialog", "       품명"))
        self.label_6.setText(_translate("MainDialog", "    매입가"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainDialog", "  매 입  "))
        self.c_pushButton_com_search.setText(_translate("MainDialog", "회사 검색"))
        self.label_14.setText(_translate("MainDialog", "~"))
        self.label_19.setText(_translate("MainDialog", " 기간:"))
        item = self.c_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainDialog", "거래일"))
        item = self.c_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainDialog", "품번"))
        item = self.c_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainDialog", "품명"))
        item = self.c_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainDialog", "단가"))
        item = self.c_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainDialog", "갯수"))
        item = self.c_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainDialog", "공급 가액"))
        item = self.c_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainDialog", "세액"))
        self.c_pushButton_search.setText(_translate("MainDialog", "조 회"))
        self.c_pushButton_delete.setText(_translate("MainDialog", "삭 제"))
        self.label_20.setText(_translate("MainDialog", "공급 가액:"))
        self.c_label_price.setText(_translate("MainDialog", "0"))
        self.label_26.setText(_translate("MainDialog", "원"))
        self.label_22.setText(_translate("MainDialog", "세 액:"))
        self.c_label_tax.setText(_translate("MainDialog", "0"))
        self.label_27.setText(_translate("MainDialog", "원"))
        self.label_24.setText(_translate("MainDialog", "합 계:"))
        self.c_label_total.setText(_translate("MainDialog", "0"))
        self.label_28.setText(_translate("MainDialog", "원"))
        self.label_com_name.setText(_translate("MainDialog", "     회사명: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainDialog", " 회사 조회 "))
        item = self.r_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainDialog", "            회사명            "))
        item = self.r_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainDialog", "            미수금            "))
        self.r_pushButton_search.setText(_translate("MainDialog", "검 색"))
        self.r_pushButton_detail.setText(_translate("MainDialog", "자세히"))
        self.r_pushButton_receive.setText(_translate("MainDialog", "수 금"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainDialog", "  미수금  "))
        self.rg_pushButton.setText(_translate("MainDialog", "등  록"))
        self.label_2.setText(_translate("MainDialog", "       업체명"))
        self.label_17.setText(_translate("MainDialog", "사업자 번호"))
        self.label_16.setText(_translate("MainDialog", "         성 명"))
        self.label_18.setText(_translate("MainDialog", "\n"
"        Developed by DaeHyeon\n"
"           ndh8392@gmail.com"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainDialog", " 업체 등록 "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainDialog = QtWidgets.QDialog()
    ui = Ui_MainDialog()
    ui.setupUi(MainDialog)
    MainDialog.show()
    sys.exit(app.exec_())

