# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './product_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_product_Dialog(object):
    def setupUi(self, product_Dialog):
        product_Dialog.setObjectName("product_Dialog")
        product_Dialog.resize(650, 431)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Downloads/st_mark_icons/st_mark_iTO_2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        product_Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(product_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.p_tableWidget = QtWidgets.QTableWidget(product_Dialog)
        self.p_tableWidget.setObjectName("p_tableWidget")
        self.p_tableWidget.setColumnCount(5)
        self.p_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.p_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.p_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.p_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.p_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.p_tableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.p_tableWidget, 3, 0, 1, 11)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(product_Dialog)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 11)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.p_pushButton_search = QtWidgets.QPushButton(product_Dialog)
        self.p_pushButton_search.setStyleSheet("font: 10pt \"나눔스퀘어\";\n"
"")
        self.p_pushButton_search.setAutoDefault(True)
        self.p_pushButton_search.setObjectName("p_pushButton_search")
        self.gridLayout.addWidget(self.p_pushButton_search, 2, 10, 1, 1)
        self.p_lineEdit_search = QtWidgets.QLineEdit(product_Dialog)
        self.p_lineEdit_search.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p_lineEdit_search.setObjectName("p_lineEdit_search")
        self.gridLayout.addWidget(self.p_lineEdit_search, 2, 9, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        self.p_pushButton_select = QtWidgets.QPushButton(product_Dialog)
        self.p_pushButton_select.setStyleSheet("font: 10pt \"나눔스퀘어\";\n"
"")
        self.p_pushButton_select.setAutoDefault(False)
        self.p_pushButton_select.setObjectName("p_pushButton_select")
        self.gridLayout.addWidget(self.p_pushButton_select, 4, 10, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 9, 1, 1)
        self.frame = QtWidgets.QFrame(product_Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 1, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 8, 1, 1)
        self.label_2 = QtWidgets.QLabel(product_Dialog)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 4, 1, 2)
        self.label_3 = QtWidgets.QLabel(product_Dialog)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 4, 0, 1, 1)
        self.p_label_price = QtWidgets.QLabel(product_Dialog)
        self.p_label_price.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        self.p_label_price.setFont(font)
        self.p_label_price.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p_label_price.setObjectName("p_label_price")
        self.gridLayout.addWidget(self.p_label_price, 4, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 4, 7, 1, 1)

        self.retranslateUi(product_Dialog)
        QtCore.QMetaObject.connectSlotsByName(product_Dialog)

    def retranslateUi(self, product_Dialog):
        _translate = QtCore.QCoreApplication.translate
        product_Dialog.setWindowTitle(_translate("product_Dialog", "제품 검색"))
        self.p_tableWidget.setSortingEnabled(True)
        item = self.p_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("product_Dialog", "품번"))
        item = self.p_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("product_Dialog", "품명"))
        item = self.p_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("product_Dialog", "매입처"))
        item = self.p_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("product_Dialog", "매입가"))
        item = self.p_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("product_Dialog", "재고"))
        self.label.setText(_translate("product_Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">제품 검색</span></p></body></html>"))
        self.p_pushButton_search.setText(_translate("product_Dialog", "검 색"))
        self.p_pushButton_select.setText(_translate("product_Dialog", "선 택"))
        self.label_2.setText(_translate("product_Dialog", "원"))
        self.label_3.setText(_translate("product_Dialog", "최근 단가: "))
        self.p_label_price.setText(_translate("product_Dialog", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    product_Dialog = QtWidgets.QDialog()
    ui = Ui_product_Dialog()
    ui.setupUi(product_Dialog)
    product_Dialog.show()
    sys.exit(app.exec_())

